### ISSUE TITLE
Inquiry Regarding Data and Implementation for Reproducing Results from Study

### ISSUE THREAD

**Issue by theoutca** [TaewiKim/Fly-by-Feel#1]
The dataset shared appears incomplete, and some experimental training data is missing. Could you kindly provide the detailed datasets for the five experiments mentioned in the paper?

**Comment by TaewiKim** [comment]
If you wish to request additional data beyond the materials disclosed in this repository, please contact the corresponding author, specifying your affiliation and the intended purpose of use.
